query getAttacks($limit: Int!, $offset: Int!) {
  attacks(limit: $limit, offset: $offset, order_by: { created_at: desc }) {
    id
    created_at
    employee {
      firstname
      lastname
    }
    campaign {
      name
    }
    status
  }
}
